[2024-01-30T20:45:15.638-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=scheduled__2024-01-30T23:30:00+00:00/task_id=wait_for_step permission to 509
[2024-01-30T20:45:15.733-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=scheduled__2024-01-30T23:30:00+00:00/task_id=wait_for_step permission to 509
[2024-01-30T20:45:15.762-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-3.wait_for_step scheduled__2024-01-30T23:30:00+00:00 [queued]>
[2024-01-30T20:45:15.784-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-3.wait_for_step scheduled__2024-01-30T23:30:00+00:00 [queued]>
[2024-01-30T20:45:15.785-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-30T20:45:15.884-0300] {taskinstance.py:1382} INFO - Executing <Task(EmrStepSensor): wait_for_step> on 2024-01-30 23:30:00+00:00
[2024-01-30T20:45:15.887-0300] {standard_task_runner.py:57} INFO - Started process 147 to run task
[2024-01-30T20:45:15.891-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-3', 'wait_for_step', 'scheduled__2024-01-30T23:30:00+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmppbpjccjc']
[2024-01-30T20:45:15.893-0300] {standard_task_runner.py:85} INFO - Job 310: Subtask wait_for_step
[2024-01-30T20:45:16.027-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-3/run_id=scheduled__2024-01-30T23:30:00+00:00/task_id=wait_for_step permission to 509
[2024-01-30T20:45:16.029-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-3.wait_for_step scheduled__2024-01-30T23:30:00+00:00 [running]> on host 14111-NB.
[2024-01-30T20:45:16.267-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-3' AIRFLOW_CTX_TASK_ID='wait_for_step' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-30T23:30:00+00:00'
[2024-01-30T20:45:16.289-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-01-30T20:45:16.290-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-01-30T20:45:16.517-0300] {emr.py:575} INFO - Poking step s-01344841S6MS18W1LE9P on cluster j-3VYL44CY0T6LV
[2024-01-30T20:45:17.783-0300] {emr.py:79} INFO - Job flow currently PENDING
[2024-01-30T20:46:17.844-0300] {emr.py:575} INFO - Poking step s-01344841S6MS18W1LE9P on cluster j-3VYL44CY0T6LV
[2024-01-30T20:46:19.071-0300] {emr.py:79} INFO - Job flow currently PENDING
[2024-01-30T20:47:19.075-0300] {emr.py:575} INFO - Poking step s-01344841S6MS18W1LE9P on cluster j-3VYL44CY0T6LV
[2024-01-30T20:47:20.242-0300] {emr.py:79} INFO - Job flow currently PENDING
[2024-01-30T20:48:20.302-0300] {emr.py:575} INFO - Poking step s-01344841S6MS18W1LE9P on cluster j-3VYL44CY0T6LV
[2024-01-30T20:48:21.552-0300] {emr.py:79} INFO - Job flow currently PENDING
[2024-01-30T20:49:21.614-0300] {emr.py:575} INFO - Poking step s-01344841S6MS18W1LE9P on cluster j-3VYL44CY0T6LV
[2024-01-30T20:49:22.947-0300] {emr.py:79} INFO - Job flow currently PENDING
[2024-01-30T20:50:23.008-0300] {emr.py:575} INFO - Poking step s-01344841S6MS18W1LE9P on cluster j-3VYL44CY0T6LV
[2024-01-30T20:50:24.315-0300] {emr.py:79} INFO - Job flow currently PENDING
[2024-01-30T20:51:24.376-0300] {emr.py:575} INFO - Poking step s-01344841S6MS18W1LE9P on cluster j-3VYL44CY0T6LV
[2024-01-30T20:51:25.698-0300] {emr.py:79} INFO - Job flow currently PENDING
[2024-01-30T20:52:25.755-0300] {emr.py:575} INFO - Poking step s-01344841S6MS18W1LE9P on cluster j-3VYL44CY0T6LV
[2024-01-30T20:52:26.991-0300] {emr.py:79} INFO - Job flow currently RUNNING
[2024-01-30T20:53:27.020-0300] {emr.py:575} INFO - Poking step s-01344841S6MS18W1LE9P on cluster j-3VYL44CY0T6LV
[2024-01-30T20:53:28.275-0300] {emr.py:79} INFO - Job flow currently FAILED
[2024-01-30T20:53:28.287-0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/sensors/emr.py", line 624, in execute
    super().execute(context=context)
  File "/usr/local/lib/python3.10/dist-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/usr/local/lib/python3.10/dist-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/amazon/aws/sensors/emr.py", line 85, in poke
    raise AirflowException(f"EMR job failed: {self.failure_message_from_response(response)}")
airflow.exceptions.AirflowException: EMR job failed: for reason None with message pyspark.errors.exceptions.captured.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `list`.`dt` cannot be resolved. Did you mean one of the following? [`city`, `latitude`, `city_id`, `cod`, `longitude`].; and log file s3://how-desafio-3/logs/emr/j-3VYL44CY0T6LV/steps/s-01344841S6MS18W1LE9P/stdout.gz
[2024-01-30T20:53:28.291-0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=how-desafio-3, task_id=wait_for_step, execution_date=20240130T233000, start_date=20240130T234515, end_date=20240130T235328
[2024-01-30T20:53:28.338-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 310 for task wait_for_step (EMR job failed: for reason None with message pyspark.errors.exceptions.captured.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `list`.`dt` cannot be resolved. Did you mean one of the following? [`city`, `latitude`, `city_id`, `cod`, `longitude`].; and log file s3://how-desafio-3/logs/emr/j-3VYL44CY0T6LV/steps/s-01344841S6MS18W1LE9P/stdout.gz; 147)
[2024-01-30T20:53:28.356-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-30T20:53:28.387-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
