[2024-01-26T13:30:02.840-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T16:15:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T13:30:02.875-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T16:15:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T13:30:02.888-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T16:15:00+00:00 [queued]>
[2024-01-26T13:30:02.897-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T16:15:00+00:00 [queued]>
[2024-01-26T13:30:02.898-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-26T13:30:02.923-0300] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2024-01-26 16:15:00+00:00
[2024-01-26T13:30:02.925-0300] {standard_task_runner.py:57} INFO - Started process 3633 to run task
[2024-01-26T13:30:02.927-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'how-desafio-03', 'invoke_lambda_function', 'scheduled__2024-01-26T16:15:00+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpkf65sckx']
[2024-01-26T13:30:02.928-0300] {standard_task_runner.py:85} INFO - Job 224: Subtask invoke_lambda_function
[2024-01-26T13:30:02.986-0300] {logging_mixin.py:151} INFO - Changing /mnt/c/Users/filipe.macedo_ifood/Documents/how-desafio-03/airflow/logs/dag_id=how-desafio-03/run_id=scheduled__2024-01-26T16:15:00+00:00/task_id=invoke_lambda_function permission to 509
[2024-01-26T13:30:02.989-0300] {task_command.py:416} INFO - Running <TaskInstance: how-desafio-03.invoke_lambda_function scheduled__2024-01-26T16:15:00+00:00 [running]> on host 14111-NB.
[2024-01-26T13:30:03.094-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='how-desafio-03' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2024-01-26T16:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-26T16:15:00+00:00'
[2024-01-26T13:30:03.095-0300] {lambda_function.py:211} INFO - Invoking AWS Lambda function: how-desafio-03 with payload: {"date": "1706286600"}
[2024-01-26T13:30:03.105-0300] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-01-26T13:30:03.106-0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-01-26T13:30:04.073-0300] {lambda_function.py:220} INFO - Lambda response metadata: {'RequestId': '2f01de09-2f5a-4303-87ad-9b02aba22c6c', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Fri, 26 Jan 2024 16:30:25 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': '2f01de09-2f5a-4303-87ad-9b02aba22c6c', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65b3de21-1b14f0d018e9730e40dc3252;sampled=0'}, 'RetryAttempts': 0}
[2024-01-26T13:30:04.075-0300] {lambda_function.py:230} INFO - Lambda function invocation succeeded: {'RequestId': '2f01de09-2f5a-4303-87ad-9b02aba22c6c', 'HTTPStatusCode': 202, 'HTTPHeaders': {'date': 'Fri, 26 Jan 2024 16:30:25 GMT', 'content-length': '0', 'connection': 'keep-alive', 'x-amzn-requestid': '2f01de09-2f5a-4303-87ad-9b02aba22c6c', 'x-amzn-remapped-content-length': '0', 'x-amzn-trace-id': 'root=1-65b3de21-1b14f0d018e9730e40dc3252;sampled=0'}, 'RetryAttempts': 0}
[2024-01-26T13:30:04.154-0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=how-desafio-03, task_id=invoke_lambda_function, execution_date=20240126T161500, start_date=20240126T163002, end_date=20240126T163004
[2024-01-26T13:30:04.188-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-26T13:30:04.204-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
